# Decision-curve data at 10 years.
#
# The survey-design-based categorical NRI and its JKn confidence interval are
# generated by test_S7_discrimination.R so that the discrimination and NRI
# estimates use the same refitted survey replicate models.
# Auto-organized from the verified pipeline; logic unchanged.

source("06_R_Code/00_config.R")

cohort <- prepare_cohort(readRDS(file.path(paths$data, "cohort_primary_v2.rds")))
crp <- readRDS(file.path(paths$data, "crp_harmonized.rds"))
crp_index <- match(cohort$SEQN, crp$SEQN)
cohort$crp_mg_l <- crp$crp_mgL[crp_index]
cohort$crp_assay <- crp$crp_assay[crp_index]
cohort$log_crp <- log(cohort$crp_mg_l)

# CBC fields are rebuilt directly from the supplied legacy and contemporary
# laboratory domains.
raw_domains <- readRDS(file.path(paths$data, "raw_domains.rds"))
cbc_columns <- c("SEQN", "LBXHGB", "LBXWBCSI", "LBXPLTSI", "LBXRDW")
cbc <- rbind(
  raw_domains$cbc_legacy[, cbc_columns],
  raw_domains$cbc[, cbc_columns]
)
cbc <- cbc[!duplicated(cbc$SEQN), ]
cbc_index <- match(cohort$SEQN, cbc$SEQN)
cohort$hemoglobin <- cbc$LBXHGB[cbc_index]
cohort$wbc <- cbc$LBXWBCSI[cbc_index]
cohort$platelets <- cbc$LBXPLTSI[cbc_index]
cohort$rdw <- cbc$LBXRDW[cbc_index]
full_design <- make_design(cohort)
# Decision curves at 10 years (retained as a non-submission diagnostic).
nri_variables <- unique(c(
  "ftime_years", "death_allcause", "uacr_cat", model_terms$M3,
  "wt_pooled", "psu"
))
nri_data <- cohort[complete.cases(cohort[, nri_variables]), ]
nri_data$analysis_weight <- nri_data$wt_pooled / mean(nri_data$wt_pooled)
clinical_formula <- Surv(ftime_years, death_allcause) ~
  age + sex_female + race_eth + cycle + bmi + smoking + dm_main + bp_stage + egfr
clinical_fit <- coxph(
  clinical_formula, data = nri_data, weights = analysis_weight,
  robust = TRUE, cluster = psu, x = TRUE
)
uacr_fit <- coxph(
  update(clinical_formula, . ~ . + uacr_cat), data = nri_data,
  weights = analysis_weight, robust = TRUE, cluster = psu, x = TRUE
)
uacr_log2_fit <- coxph(
  update(clinical_formula, . ~ . + uacr_log2), data = nri_data,
  weights = analysis_weight, robust = TRUE, cluster = psu, x = TRUE
)

predict_10y_risk <- function(fit, data) {
  baseline <- basehaz(fit, centered = FALSE)
  baseline_10 <- baseline$hazard[max(which(baseline$time <= 10))]
  linear_predictor <- predict(fit, newdata = data, type = "lp", reference = "zero")
  1 - exp(-baseline_10 * exp(linear_predictor))
}
nri_data$risk_clinical <- predict_10y_risk(clinical_fit, nri_data)
nri_data$risk_uacr <- predict_10y_risk(uacr_fit, nri_data)
nri_data$risk_uacr_log2 <- predict_10y_risk(uacr_log2_fit, nri_data)

# Marginal weighted Kaplan-Meier estimate of the censoring distribution.
censor_times <- sort(unique(nri_data$ftime_years[
  nri_data$death_allcause == 0 & nri_data$ftime_years <= 10
]))
g_after <- numeric(length(censor_times))
g_current <- 1
for (index in seq_along(censor_times)) {
  current_time <- censor_times[index]
  at_risk <- sum(nri_data$analysis_weight[nri_data$ftime_years >= current_time])
  censored <- sum(nri_data$analysis_weight[
    nri_data$ftime_years == current_time & nri_data$death_allcause == 0
  ])
  g_current <- g_current * (1 - censored / at_risk)
  g_after[index] <- g_current
}
g_before <- function(time) {
  index <- max(which(censor_times < time), 0)
  if (index == 0) 1 else g_after[index]
}
g_10 <- if (any(censor_times <= 10)) g_after[max(which(censor_times <= 10))] else 1
nri_data$status_10 <- ifelse(
  nri_data$death_allcause == 1 & nri_data$ftime_years <= 10, 1,
  ifelse(nri_data$ftime_years > 10, 0, NA)
)
nri_data$ipcw <- 0
event_rows <- which(nri_data$status_10 == 1)
nonevent_rows <- which(nri_data$status_10 == 0)
nri_data$ipcw[event_rows] <- vapply(
  nri_data$ftime_years[event_rows], g_before, numeric(1)
)
nri_data$ipcw[event_rows] <- 1 / nri_data$ipcw[event_rows]
nri_data$ipcw[nonevent_rows] <- 1 / g_10
nri_data$final_weight <- nri_data$analysis_weight * nri_data$ipcw

risk_bands <- c(0, 0.05, 0.10, 0.20, Inf)
old_band <- as.numeric(cut(nri_data$risk_clinical, risk_bands,
                           right = FALSE, include.lowest = TRUE))
new_band <- as.numeric(cut(nri_data$risk_uacr, risk_bands,
                           right = FALSE, include.lowest = TRUE))
movement <- sign(new_band - old_band)
weighted_movement <- function(rows, favorable_direction) {
  denominator <- sum(nri_data$final_weight[rows])
  favorable <- sum(nri_data$final_weight[rows & movement == favorable_direction])
  unfavorable <- sum(nri_data$final_weight[rows & movement == -favorable_direction])
  (favorable - unfavorable) / denominator
}
is_event <- !is.na(nri_data$status_10) & nri_data$status_10 == 1
is_nonevent <- !is.na(nri_data$status_10) & nri_data$status_10 == 0
nri_event <- weighted_movement(is_event, 1)
nri_nonevent <- weighted_movement(is_nonevent, -1)
thresholds <- seq(0.01, 0.30, by = 0.01)
total_weight <- sum(nri_data$final_weight)
net_benefit <- function(risk, threshold) {
  positive <- risk >= threshold
  true_positive <- sum(nri_data$final_weight[positive & is_event]) / total_weight
  false_positive <- sum(nri_data$final_weight[positive & is_nonevent]) / total_weight
  true_positive - false_positive * threshold / (1 - threshold)
}
dca_rows <- do.call(rbind, lapply(thresholds, function(threshold) {
  event_prevalence <- sum(nri_data$final_weight[is_event]) / total_weight
  rbind(
    data.frame(threshold = threshold, model = "Clinical model",
               net_benefit = net_benefit(nri_data$risk_clinical, threshold)),
    data.frame(threshold = threshold, model = "Clinical model + UACR (categorical)",
               net_benefit = net_benefit(nri_data$risk_uacr, threshold)),
    data.frame(threshold = threshold, model = "Clinical model + log2(UACR)",
               net_benefit = net_benefit(nri_data$risk_uacr_log2, threshold)),
    data.frame(threshold = threshold, model = "Treat all",
               net_benefit = event_prevalence -
                 (1 - event_prevalence) * threshold / (1 - threshold)),
    data.frame(threshold = threshold, model = "Treat none", net_benefit = 0)
  )
}))
write.csv(dca_rows, file.path(paths$tables, "S12_decision_curve.csv"),
          row.names = FALSE)
