# Summary: Draws the full-spectrum restricted-cubic-spline figure (Figure 4) for continuous UACR.
# =============================================================================
# 44_rcs_fullspectrum.R
# Restricted cubic spline: continuous UACR -> mortality, on the REBUILT
# full BP-treatment-spectrum primary cohort (six BP categories).
# -----------------------------------------------------------------------------
# Main outcome  : all-cause mortality  -> Figure4_RCS_UACR_AllCause.{tiff,png,pdf}
# Supplement    : heart-disease death  -> Supplement_RCS_UACR_HeartDisease.{...}
#
# Model (PI Model 3, updated): age, sex, race/ethnicity, NHANES cycle, BMI,
#   smoking, diabetes composite, six-level BP-treatment category, continuous
#   eGFR (CKD-EPI 2021).  UACR enters as rms::rcs(log2 UACR, 4 knots).
# Reference HR = UACR 10 mg/g.  CI is reference-anchored (pinches to 1.0 at 10).
# Pooled MEC weights + SDMVSTRA/SDMVPSU complex design (already in cohort_full).
# =============================================================================

suppressPackageStartupMessages({
  library(survey); library(survival); library(rms)
  library(ggplot2); library(patchwork); library(scales); library(ragg)
})
options(warn = 1, survey.lonely.psu = "adjust")
source("06_R_Code/supplementary_figure_generators/helpers/04_theme_jacc.R")   # palette, save_fig_all
OUTDIR <- "06_R_Code/supplementary_figure_generators/output"

# ---- Rebuild full-spectrum PRIMARY cohort -----------------------------------
coh <- readRDS("07_R_Data/cohort_for_figures.rds")
coh <- subset(coh, bp_stage != "Treated (BP unmeasured)")
coh$bp_stage <- droplevels(coh$bp_stage)
coh$uacr_cat <- droplevels(coh$uacr_cat)
# heart-disease-only endpoint (UCOD 001) for the secondary RCS
.m <- readRDS("07_R_Data/mortality.rds"); .u <- .m$UCOD_LEADING[match(coh$SEQN,.m$SEQN)]
coh$death_hd <- as.integer(coh$death_allcause==1 & .u=="001"); coh$death_hd[is.na(coh$death_hd)] <- 0L
des <- svydesign(ids = ~psu, strata = ~strata, weights = ~wt_pooled,
                 nest = TRUE, data = coh)

cat(sprintf("Full-spectrum cohort: n=%s | BP levels=%d | all-cause=%d | CVD=%d\n",
    format(nrow(coh), big.mark = ","), nlevels(coh$bp_stage),
    sum(coh$death_allcause == 1), sum(coh$death_hd == 1)))

# ---- Knots (prespecified 4-knot strategy on log2 UACR) ----------------------
KQ     <- c(.05, .35, .65, .95)
knots  <- as.numeric(quantile(coh$uacr_log2, KQ, na.rm = TRUE))
knots_expr <- paste0("c(", paste(sprintf("%.10g", knots), collapse = ","), ")")
knots_mgg  <- 2^knots
cat("Knots (log2):", paste(round(knots, 3), collapse = ", "),
    "\nKnots (mg/g):", paste(round(knots_mgg, 2), collapse = ", "), "\n")

# ---- Plotting range = 1st-99th percentile of observed UACR ------------------
prng <- as.numeric(quantile(coh$uacr_mgg, c(.01, .99), na.rm = TRUE))
xlo  <- prng[1]; xhi <- prng[2]
cat(sprintf("Plotted UACR range (1st-99th pct): %.2f - %.2f mg/g\n", xlo, xhi))
ticks <- c(1, 2, 3, 5, 10, 30, 100, 300, 400)
ticks <- ticks[ticks >= xlo & ticks <= xhi]

ADJ <- paste("age_years + sex + race_eth + cycle_num + bmi_kgm2 +",
             "smoking_3cat + dm_composite + bp_stage + egfr_2021")
ADJV <- c("age_years","sex","race_eth","cycle_num","bmi_kgm2",
          "smoking_3cat","dm_composite","bp_stage","egfr_2021")

fmtp <- function(p) if (is.na(p)) "n/a" else if (p < 0.0001) "< 0.0001" else
  paste0("= ", formatC(p, digits = 3, format = "g"))

# =============================================================================
# Core fitter + figure builder
# =============================================================================
rcs_fig <- function(ev, ttl, basename, ribbon, band, secondary = FALSE) {

  need <- c("ftime_years", ev, "uacr_log2", ADJV)
  cc   <- complete.cases(coh[, need]); des_cc <- subset(des, cc)
  n_mod <- sum(cc); n_ev <- sum(coh[[ev]][cc] == 1)
  cat(sprintf("[%s] complete-case n=%s, events=%s\n", ev,
              format(n_mod, big.mark = ","), format(n_ev, big.mark = ",")))

  fml  <- as.formula(sprintf("Surv(ftime_years,%s) ~ rms::rcs(uacr_log2,%s) + %s",
                             ev, knots_expr, ADJ))
  fmll <- as.formula(sprintf("Surv(ftime_years,%s) ~ uacr_log2 + %s", ev, ADJ))
  fit  <- svycoxph(fml,  design = des_cc)
  fitl <- svycoxph(fmll, design = des_cc)

  # P-nonlinearity and P-overall.  For the prespecified all-cause analysis,
  # display the design-based Wald test generated by test_S4_dose_response_spline.R
  # so the figure and machine-readable table use the same inferential test.
  p_nl <- tryCatch(as.numeric(anova(fit, fitl)$p[1]), error = function(e) NA_real_)
  if (!secondary) {
    functional_form_file <- "08_Analysis_Outputs/tables/S4_functional_form.csv"
    if (file.exists(functional_form_file)) {
      p_nl <- read.csv(functional_form_file)$p_nonlinearity[1]
    }
  }
  p_ov <- tryCatch({
    b <- coef(fit); V <- vcov(fit); ix <- grep("uacr_log2", names(b))
    W <- as.numeric(t(b[ix]) %*% solve(V[ix, ix]) %*% b[ix])
    pchisq(W, df = length(ix), lower.tail = FALSE)
  }, error = function(e) NA_real_)

  # Prediction grid (covariates fixed; they cancel in the reference contrast)
  ug   <- exp(seq(log(xlo), log(xhi), length.out = 500))
  prof <- data.frame(
    uacr_log2 = log2(ug),
    age_years = mean(coh$age_years, na.rm = TRUE),
    sex = factor("Female", levels(coh$sex)),
    race_eth = factor("Non-Hispanic White", levels(coh$race_eth)),
    cycle_num = median(coh$cycle_num, na.rm = TRUE),
    bmi_kgm2 = mean(coh$bmi_kgm2, na.rm = TRUE),
    smoking_3cat = factor("Never", levels(coh$smoking_3cat)),
    dm_composite = 0L,
    bp_stage = factor("Non-elevated BP", levels(coh$bp_stage)),
    egfr_2021 = mean(coh$egfr_2021, na.rm = TRUE))
  refrow <- prof[1, ]; refrow$uacr_log2 <- log2(10)

  # Reference-anchored CI via model-matrix contrast on the spline basis
  res <- tryCatch({
    sp <- grep("uacr_log2", names(coef(fit)), value = TRUE)
    mm <- model.matrix(delete.response(terms(fit)), data = rbind(refrow, prof))
    stopifnot(all(sp %in% colnames(mm)))
    Xr <- mm[1, sp, drop = FALSE]; Xg <- mm[-1, sp, drop = FALSE]
    D  <- sweep(Xg, 2, as.numeric(Xr), "-")
    b  <- coef(fit)[sp]; V <- vcov(fit)[sp, sp, drop = FALSE]
    lh <- as.numeric(D %*% b)
    se <- sqrt(pmax(rowSums((D %*% V) * D), 0))
    data.frame(uacr = ug, HR = exp(lh), lo = exp(lh - 1.96*se), hi = exp(lh + 1.96*se))
  }, error = function(e) {
    message("contrast CI failed, falling back to se.fit: ", conditionMessage(e))
    lp <- predict(fit, prof, type = "lp", se.fit = TRUE)
    r0 <- predict(fit, refrow, type = "lp")
    d  <- lp$fit - as.numeric(r0)
    data.frame(uacr = ug, HR = exp(d), lo = exp(d - 1.96*lp$se.fit),
               hi = exp(d + 1.96*lp$se.fit))
  })

  # HR-per-doubling (linear model) for the caption/annotation
  bl <- coef(fitl)["uacr_log2"]; sl <- sqrt(vcov(fitl)["uacr_log2","uacr_log2"])
  hr_dbl <- sprintf("%.2f (%.2f–%.2f)", exp(bl), exp(bl-1.96*sl), exp(bl+1.96*sl))

  # Point annotations at clinically meaningful UACR values
  at <- c(10, 15, 30, 100); at <- at[at >= xlo & at <= xhi]
  ann <- data.frame(uacr = at,
    HR = approx(res$uacr, res$HR, at, rule = 2)$y,
    lo = approx(res$uacr, res$lo, at, rule = 2)$y,
    hi = approx(res$uacr, res$hi, at, rule = 2)$y)
  ann$lab <- ifelse(ann$uacr == 10, "10 mg/g\nHR 1.00 (ref)",
              sprintf("%g mg/g\nHR %.2f (%.2f–%.2f)", ann$uacr, ann$HR, ann$lo, ann$hi))
  pts <- paste(sprintf("  %g mg/g: %.2f (%.2f–%.2f)",
               ann$uacr[ann$uacr != 10], ann$HR[ann$uacr != 10],
               ann$lo[ann$uacr != 10], ann$hi[ann$uacr != 10]), collapse = "\n")
  write.csv(data.frame(outcome = ev, res),
            file.path(OUTDIR, paste0(basename, "_grid.csv")), row.names = FALSE)

  # y-range
  ymax <- min(max(res$hi, na.rm = TRUE) * 1.05, 8)
  ymin <- max(min(res$lo, na.rm = TRUE) * 0.95, 0.4)
  zlo <- max(xlo, 1)
  # clip ribbon into the panel so no rows are silently dropped at the tail
  res$lo <- pmin(pmax(res$lo, ymin), ymax)
  res$hi <- pmin(pmax(res$hi, ymin), ymax)
  res$HR <- pmin(pmax(res$HR, ymin), ymax)

  # ---- Main spline panel ----------------------------------------------------
  p_main <- ggplot(res, aes(uacr, HR)) +
    # subtle background zones
    annotate("rect", xmin = zlo, xmax = 10,  ymin = ymin, ymax = ymax,
             fill = "#1F4E79", alpha = 0.04) +
    annotate("rect", xmin = 10, xmax = 30,  ymin = ymin, ymax = ymax,
             fill = band, alpha = 0.16) +
    annotate("rect", xmin = 30, xmax = xhi, ymin = ymin, ymax = ymax,
             fill = "#C0392B", alpha = 0.05) +
    geom_ribbon(aes(ymin = lo, ymax = hi), fill = ribbon, alpha = 0.18) +
    geom_line(linewidth = 1.25, colour = ribbon, lineend = "round") +
    geom_hline(yintercept = 1, linetype = "dashed", colour = "grey45", linewidth = 0.45) +
    geom_vline(xintercept = c(10, 30), linetype = "dashed",
               colour = "grey50", linewidth = 0.4) +
    # knot ticks
    annotate("point", x = knots_mgg[knots_mgg >= xlo & knots_mgg <= xhi],
             y = ymin, shape = 17, size = 1.9, colour = "grey35") +
    # point annotations
    geom_point(data = ann, aes(uacr, HR), inherit.aes = FALSE,
               shape = 21, size = 2.8, fill = "white", colour = ribbon, stroke = 1.1) +
    annotate("text", x = zlo, y = ymax,
             label = sprintf("HR per doubling: %s\nP-overall %s\n \nHR vs UACR 10 mg/g (ref):\n%s",
                             hr_dbl, fmtp(p_ov), pts),
             hjust = 0, vjust = 1, size = 2.85, lineheight = 1.15, colour = "grey20") +
    annotate("text", x = c(sqrt(zlo*10), sqrt(10*30), sqrt(30*xhi)), y = ymin,
             label = c("normal\n(<10)", "low-grade\n(10–29)", "albuminuria\n(≥30)"),
             vjust = -0.3, size = 2.6, colour = "grey40", fontface = "italic", lineheight = 0.9) +
    scale_x_continuous(trans = "log10", breaks = ticks, labels = ticks,
                       limits = c(xlo, xhi), expand = c(0.01, 0)) +
    scale_y_continuous(trans = "log", breaks = c(0.5,1,2,3,4,6,8),
                       labels = c("0.5","1.0","2.0","3.0","4.0","6.0","8.0"),
                       limits = c(ymin, ymax), expand = c(0, 0)) +
    labs(title = ttl, x = NULL,
         y = paste0("Adjusted hazard ratio for\n",
                    if (secondary) "heart-disease mortality" else "all-cause mortality")) +
    theme_classic(base_size = 12) +
    theme(plot.title = element_text(size = 13, face = "bold", hjust = 0,
                                    margin = margin(b = 6)),
          axis.text = element_text(size = 11, colour = "black"),
          axis.title.y = element_text(size = 12, margin = margin(r = 6)),
          panel.grid.major.y = element_line(colour = "grey92", linewidth = 0.3),
          axis.line = element_line(colour = "grey35", linewidth = 0.4),
          plot.margin = margin(8, 12, 0, 8))

  # ---- Weighted distribution strip (shared x-axis) --------------------------
  dd <- data.frame(uacr = pmin(pmax(coh$uacr_mgg[cc], xlo), xhi),
                   w = coh$wt_pooled[cc])
  p_dist <- ggplot(dd, aes(uacr, weight = w)) +
    geom_histogram(bins = 46, fill = "grey55", colour = "white", linewidth = 0.12) +
    geom_vline(xintercept = c(10, 30), linetype = "dashed",
               colour = "grey50", linewidth = 0.4) +
    scale_x_continuous(trans = "log10", breaks = ticks, labels = ticks,
                       limits = c(xlo, xhi), expand = c(0.01, 0)) +
    scale_y_continuous(breaks = NULL, expand = expansion(mult = c(0, 0.05))) +
    labs(x = "Urinary albumin-to-creatinine ratio, mg/g", y = "Survey-weighted\ndensity") +
    theme_classic(base_size = 12) +
    theme(axis.text.x = element_text(size = 11, colour = "black"),
          axis.title.x = element_text(size = 12, margin = margin(t = 6)),
          axis.title.y = element_text(size = 8, colour = "grey40", angle = 0,
                                      vjust = 0.5, hjust = 1),
          axis.line.y = element_blank(), axis.ticks.y = element_blank(),
          plot.margin = margin(0, 12, 6, 8))

  fig <- p_main / p_dist + plot_layout(heights = c(4.2, 1))
  save_fig_all(fig, basename, width = 7.6, height = 6.6, dpi = 600, dir = OUTDIR)

  cat(sprintf("[%s] saved %s | P-overall %s | P-nl %s | HR/doubling %s\n\n",
              ev, basename, fmtp(p_ov), fmtp(p_nl), hr_dbl))
  list(ev = ev, n = n_mod, events = n_ev, p_overall = p_ov, p_nonlin = p_nl,
       hr_doubling = hr_dbl, ann = ann, knots_mgg = knots_mgg,
       range = c(xlo, xhi))
}

# This script produces the MATCHED continuous-UACR restricted-cubic-spline pair
# with an identical survey-weighted-density panel:
#   Figure 4 (all-cause)  and  Supplementary Figure S7 (heart-disease).
OUTDIR <- "08_Analysis_Outputs/figures"
dir.create(OUTDIR, showWarnings = FALSE, recursive = TRUE)

# ---- Main: all-cause (Figure 4) ---------------------------------------------
ac <- rcs_fig("death_allcause",
              NULL,
              "Figure_4_RCS_Continuous_UACR",
              ribbon = "#B80F1A", band = "#E08E2A", secondary = FALSE)

# ---- Supplement: heart-disease mortality (Supplementary Figure S7) ----------
cv <- rcs_fig("death_hd",
              NULL,
              "Supplementary_Figure_S7_RCS_Continuous_HeartDisease",
              ribbon = "#0759A3", band = "#E08E2A", secondary = TRUE)

saveRDS(list(allcause = ac, cvd = cv, knots_log2 = knots, knots_mgg = knots_mgg,
             range = c(xlo, xhi), knot_pct = KQ),
        "08_Analysis_Outputs/rcs_fullspectrum_fits.rds")

cat("\n================ RCS SUMMARY ================\n")
cat(sprintf("Knots at percentiles %s of log2(UACR)\n",
            paste0(KQ*100, collapse = "/")))
cat(sprintf("Knot UACR values: %s mg/g\n", paste(round(knots_mgg, 2), collapse = ", ")))
cat(sprintf("Plotted range: %.2f - %.2f mg/g (1st-99th pct)\n", xlo, xhi))
cat("ALL-CAUSE: ", ac$hr_doubling, " per doubling; P-overall ", fmtp(ac$p_overall),
    "; P-nl ", fmtp(ac$p_nonlin), "\n")
print(ac$ann[, c("uacr","HR","lo","hi")])
cat("44_rcs_fullspectrum.R complete.\n")
